### ISSUE TITLE
Add OpenPGP Policy generation reusable workflow

### ISSUE THREAD

**Issue by emgrav** [famedly/github-workflows#38]
As part of the effort to authenticate commit signatures across all our repos, we should add a new reusable workflow to generate the policy file from a policy config. The file should be generated using the script below, written in nuscript. Please note that the script currently only takes a single team as an input, it should be adapted to take a list of teams instead. This is to allow for situations where multiple teams may be codeowners in repository.

```nu
#!/usr/bin/env nu
def main [team: string] {
	rm openpgp-policy.toml
	let users = open users.yml | get users | transpose email fingerprint
	$users | par-each {|user| sq wkd get $user.email }
	let role_overrides = open users.yml | get teams | get $team
	$users | each {|user|
		if ($role_overrides | get -i $user.email) == null {
			sq-git policy authorize --committer $user.email $user.fingerprint
		} else if ($role_overrides | get -i $user.email) == "project-maintainer" {
			sq-git policy authorize --project-maintainer $user.email $user.fingerprint
		} else if ($role_overrides | get -i $user.email) == "release-manager" {
			sq-git policy authorize --release-manager $user.email $user.fingerprint
		}
	}
	echo "Successfully regenerated openpgp-policy.toml"
}
```

An example policy config looks like this (note this is out of date):
```yaml
users:
  a.lovelace@famedly.com: 8C4869814B0D6CFB3CD10F311F4E40EBAB7A7076
  c.kussowski@famedly.com: 995D94254C14D84A51A4A7A1281DE50ACFA0AC70
  e.alicke@famedly.com: ACB7C63B9F2AECBF23AD3E98CCC925E0B8924C34
  e.dietrich@famedly.com: 9ACBAA9260AAA2CD11BFCB063417BD1163861C83
  e.graven@famedly.com: 3061EE49E60ABC7A6FD2C4A089A1D21ADC4AD1D9
  f.dommes@famedly.com: 2051EF8C7CCE4A59F3D462E8E799681FE9705796
  h.kamenov@famedly.com: CC31659B20067636D6A7AABBCC5AD96A3D245FB9
  j.gruenhage@famedly.com: 09E8418B46B53B0F825DE4BE018ACF465280F466
  j.nirve@famedly.com: AD4A1A09531D49545F0157696402F3BA59C5FA18
  j.reichmann@famedly.com: 5E0A9CB3980657CB9AB94AE6790EAEC8F99AB41F
  k.skomski@famedly.com: 8CE87D0A71A433ED5EF6053010AA5938CACF94D9
  l.kaiser@famedly.com: E992B67AFB37C7E3DF2C7C7C4F2196E814E550E1
  l.lihotzki@famedly.com: 84D1D17350A18995C0BCFD5E970DB544FA962851
  m.errenst@famedly.com: 84C80D76B38E56849194B27A630BD877138DA04C
  n.werner@famedly.com: 1A063E1EE4BAB762C339D8045FA6B2A02D13B144
  p.hettich@famedly.com: 221360EA44C6834023FF083E2498DD77FBAC46B8
  p.iov@famedly.com: 1B9EA4C27D431B9ECBBCF27A2D76C48919B64673
  s.fleer@famedly.com: 6AFCC2184CF487AD0567F54E38E74E644AE5E3DE
  s.yilmaz@famedly.com: 65CACC1553107A22B5CDD696BF4B5516695A5D16
teams:
  infrastructure:
    j.gruenhage@famedly.com: project-maintainer
    j.reichmann@famedly.com: project-maintainer
    l.kaiser@famedly.com: project-maintainer
    e.alicke@famedly.com: release-manager
    l.lihotzki@famedly.com: release-manager
    s.fleer@famedly.com: release-manager
    s.yilmaz@famedly.com: release-manager
  workflows:
    e.graven@famedly.com: project-maintainer
    f.dommes@famedly.com: project-maintainer
    p.iov@famedly.com: project-maintainer
    a.lovelace@famedly.com: release-manager
    e.dietrich@famedly.com: release-manager
    h.kamenov@famedly.com: release-manager
    k.skomski@famedly.com: release-manager
  instant_messaging:
    c.kussowski@famedly.com: project-maintainer
    n.werner@famedly.com: project-maintainer
    p.iov@famedly.com: project-maintainer
    j.nirve@famedly.com: release-manager
    m.errenst@famedly.com: release-manager
    p.hettich@famedly.com: release-manager
```

The intent is that this reusable workflow will be consumed in every repository, and configured to run on an interval, e.g. daily. If there have been changes to the policy, the workflow should open a PR to update it. An existing member of the team in question authorised to make changes will then have to check out this branch, recommit it with --reset-author, and then push to the branch. After review, this can then be merged.

This action will likely be useful for setting up a nushell environment: https://github.com/marketplace/actions/setup-nu

### Inputs
`teams`: List of strings.
Example: `['instant_messaging', 'workflows']`

### Logic
1. Check out https://github.com/famedly/openpgp-policy containing the policy config
2. Use the script above to generate an openpgp-policy.toml from the config
3. Diff the newly generated policy against the one already existing in the current repo
4. If the existing policy is identical to the newly generated one, the workflow should terminate indicating success. If they differ or a policy does not already exist, keep going.
5. Create a git commit with the newly generated policy in the current repo
6. Push it to a branch
7. Open a PR
